gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#76946A"
      - bold
    inactiveBorderColor:
      - "#54546D"
    optionsTextColor:
      - "#7E9CD8"
    selectedLineBgColor:
      - "#2A2A37"
    cherryPickedCommitBgColor:
      - "#2A2A37"
    cherryPickedCommitFgColor:
      - "#76946A"
    unstagedChangesColor:
      - "#C34043"
    defaultFgColor:
      - "#DCD7BA"
    searchingActiveBorderColor:
      - "#C0A36E"
git:
  skipHookPrefix: WIP
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server $NVIM --remote-send ''<cmd>close<cr><cmd>EditFromLazygit {{filename}}<CR>'')'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || nvim --server $NVIM --remote-send ''<cmd>close<CR><cmd>EditLineFromLazygit {{filename}} {{line}}<CR>'''
customCommands:
  - key: "X"
    context: "global"
    description: "AI commit message"
    command: "lgaicm-commit"
    output: terminal
