gui:
  nerdFontsVersion: "3"
git:
  skipHookPrefix: WIP
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server $NVIM --remote-send ''<cmd>close<cr><cmd>EditFromLazygit {{filename}}<CR>'')'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || nvim --server $NVIM --remote-send ''<cmd>close<CR><cmd>EditLineFromLazygit {{filename}} {{line}}<CR>'''
customCommands:
  - key: "x"
    context: "files"
    description: "Pick AI commit (preview)"
    output: "terminal"
    command: "$HOME/.config/lazygit/scripts/aicommit_fzf.sh"
